export const CONSTRUCT = 'CONSTRUCT';
export const COMPLETE = 'COMPLETE';
export const ADD_ELEMENT = 'ADD_ELEMENT';
export const UNGROUP_ELEMENT = 'UNGROUP_ELEMENT';
export const AREA_SELECTION = 'AREA_SELECTION';
export const UPDATE_ELEMENT_DATA = 'UPDATE_ELEMENT_DATA';
